name: Mac CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:

  run-tests-on-mac:
    # autotester.a lib provided does not conform to x64 archi, which is what github actions uses.
    runs-on: 	macos-latest
    strategy:
      matrix:
        build-type: [Release]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE/Team24/Code24/ -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{ matrix.build-type }}

    - name: Run unit tests
      run: ${{runner.workspace}}/build/src/unit_testing/unit_testing
    
    - name: Run integration tests
      run: ${{runner.workspace}}/build/src/integration_testing/integration_testing

