name: Mac CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:

  run-tests-on-mac:
    # autotester.a lib provided does not conform to x64 archi, which is what github actions uses.
    runs-on: macos-latest
    timeout-minutes: 6
    strategy:
      matrix:
        build-type: [ Release ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE/Team24/Code24/ -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config ${{ matrix.build-type }}

      - name: Run unit tests
        run: ${{runner.workspace}}/build/src/unit_testing/unit_testing

      - name: Run integration tests
        run: ${{runner.workspace}}/build/src/integration_testing/integration_testing

      # After the auto tester is run, print out the directories to check where
      # the output `xml` file is.
      - name: Print directories recursively (for debugging)
        run: ls -R

      - name: Run autotester tests
        run: |
          cd Team24/Tests24
          python ../../autotester_ci.py ${{runner.workspace}}/build/src/autotester/autotester
